ilvits_site/apps/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import SignUpView
from . import views

urlpatterns = [
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('password_reset/sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    url(r'^profile/', views.user_profile, name='user_profile'),
    # url(r'^order/(?P<order_id>[-\w]+)/$', views.user_order_detail, name='user_order_detail'),
]

ilvits_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='homepage'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),
    path('accounts/', include(('ilvits_site.apps.accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include('allauth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ilvits_site/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(
        upload_to='images/profile_pictures',
        blank=True
    )


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

ilvits_site/apps/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.CharField(max_length=254, required=True, widget=forms.TextInput(attrs={'placeholder': 'Email'}))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.last_name = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('profile_picture',)

ilvits_site/apps/accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.db import transaction

from .forms import UserForm, ProfileForm, SignUpForm


# from orders.models import Order
# from shop.views import Category


# @login_required
# def user_order_detail(request, order_id):
#     order = get_object_or_404(Order, id=order_id)
#     categories = Category.objects.all()
#     category_set = []
#     for category in categories:
#         for item in order.items.all():
#             if item.product.category == category and category not in category_set:
#                 category_set.append(category)
#
#     return render(request,
#                   'order/user_order_detail.html',
#                   {'order': order, 'category_set': category_set})
#

class SignUpView(generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/registration/signup.html'


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are logged in as  {username}.")
                return redirect("homepage")
            else:
                messages.error(request, "You have entered incorrect username or password.")
        else:
            messages.error(request, "You have entered incorrect username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="accounts/registration/login.html", context={"form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "You are logged out.")
    return redirect("homepage")


@login_required
def user_profile(request):
    return render(request, 'accounts/profile.html')


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password reset request"
                    email_template_name = "accounts/registration/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': 'ilvits.com',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@ilvits.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="accounts/registration/password_reset_form.html",
                  context={"password_reset_form": password_reset_form})


@login_required
@transaction.atomic
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, request.FILES or None, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES or None, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Updated!')
            return redirect('accounts:user_profile')
        else:
            messages.error(request, 'Please correct errors.')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'accounts/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

ilvits_site/apps/accounts/templates/accounts/edit_profile.html
{% extends "accounts/profile_base.html" %}

{% load widget_tweaks %}
{% load static %}

{% block content %}
    <div class="min-h-screen flex flex-row items-start">
    {{ block.super }}
<div class="w-4/6 p-4 bg-white rounded-lg shadow-lg border-t border-gray-50 md:max-w-sm mx-auto m-8">
<form method="post" enctype="multipart/form-data" >
  {% csrf_token %}
 {% for field in user_form %}
                <div class="mb-5 mt-4 w-sm">
                    <label for="{{ field.id_for_label }}" class="block mb-2 font-normal text-gray-600">
                        {{ field.label }}
                    </label>
                    {%  render_field field|add_class:"border border-gray-200 p-3 w-full rounded mb-" placeholder=field.label %}
                    {% for error in field.errors %}
                        <span class="text-sm text-red-400 mt-8">{{ error }}</span>
                    {% endfor %}
                </div>
            {% endfor %}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in profile_form %}
                <div class="mb-5 mt-4">
                    <label for="{{ field.id_for_label }}" class="block mb-2 font-normal text-gray-600">
                        {{ field.label }}
                    </label>
                    {%  render_field field|add_class:"border border-gray-200 p-3 w-full rounded mb-" placeholder=field.label %}
                    {% for error in field.errors %}
                        <span class="text-sm text-red-400 mt-8">{{ error }}</span>
                    {% endfor %}
                </div>
            {% endfor %}
  <button class="block w-full bg-white text-gray-800 font-bold p-4 rounded-lg shadow-md"' type="submit">Сохранить</button>
</form>
{% if form.errors %}
                    <div class="text-sm text-red-400 text-center mb-6">
                    <p>ошибка формы</p>
{{ form.errors.as_data }}


{% for error in form.errors %}
{{ error.data }} <br>
{% endfor %}
                    </div>
                {% endif %}

</div>

</div>
{% endblock %}

ilvits_site/apps/accounts/templates/accounts/profile.html
{% extends "accounts/profile_base.html" %}

{% load widget_tweaks %}
{% load static %}

{% block content %}

  <div class="min-h-screen flex flex-row items-start">
    {{ block.super }}
    <div class="flex m-8">
      defeff
    </div>
  </div>

{% endblock %}

ilvits_site/apps/accounts/templates/accounts/profile_base.html
{% extends "base.html" %}

{% block content %}
  <div class="flex flex-col w-16 md:w-56 bg-white border-r border-gray-50 backdrop-filter backdrop-blur-lg bg-opacity-70">
    <div class="flex items-center mt-3 pl-1 justify-center">
      {% if user.socialaccount_set.all.0.get_avatar_url %}
        <img class="rounded-full w-8 h-8 md:w-24 md:h-24 object-cover"
             src="{{ user.socialaccount_set.all.0.get_avatar_url }}">
      {% elif user.profile.profile_picture %}
        <img class="rounded-full w-8 h-8 md:w-24 md:h-24 object-cover" src="{{ user.profile.profile_picture.url }}">
      {% else %}
        <img class="w-8 md:w-24" src="/media/logo.svg">
      {% endif %}
    </div>
    <ul class="flex flex-col py-4 md:ml-8">
      <li>
        <a href="{% url 'accounts:user_profile' %}"
           class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mx-2" fill="none" viewBox="0 0 24 24"
               stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M10 6H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V8a2 2 0 00-2-2h-5m-4 0V5a2 2 0 114 0v1m-4 0a2 2 0 104 0m-5 8a2 2 0 100-4 2 2 0 000 4zm0 0c1.306 0 2.417.835 2.83 2M9 14a3.001 3.001 0 00-2.83 2M15 11h3m-3 4h2"></path>
          </svg>
          <span class="hidden md:inline-flex text-sm font-medium">Профиль</span>
        </a>
      </li>
      <li>
        <a href="{% url 'accounts:edit_profile' %}"
           class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mx-2" fill="none" viewBox="0 0 24 24"
               stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path>
          </svg>
          <span class="hidden md:inline-flex text-sm font-medium">Редактировать</span>
        </a>
      </li>
      <li>
        <a href="{% url 'accounts:logout' %}"
           class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mx-2" fill="none" viewBox="0 0 24 24"
               stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
          </svg>
          <span class="hidden md:inline-flex text-sm font-medium">Выйти</span>
        </a>
      </li>
    </ul>
  </div>
{% endblock %}